#!/usr/bin/env python


import os
import sys
import torch
from diffusers import StableDiffusionPipeline
from diffusers import (
    AutoencoderKL,
    DDIMScheduler,
    DDPMScheduler,
    StableDiffusionPipeline,
    UNet2DConditionModel,
)

from transformers import CLIPTextModel, CLIPTokenizer


cache_dir = "stable-diffusion-cache"
os.makedirs(cache_dir, exist_ok=True)

for model in (
    "stabilityai/stable-diffusion-2-1",
    "stabilityai/stable-diffusion-2-1-base",
):

    pipe = StableDiffusionPipeline.from_pretrained(
        model,
        cache_dir=cache_dir,
        revision="fp16",
        torch_dtype=torch.float16,
    )

    tokenizer = CLIPTokenizer.from_pretrained(
        model,
        subfolder="tokenizer",
        cache_dir=cache_dir,
        revision="fp16",
    )

    text_encoder = CLIPTextModel.from_pretrained(
        model,
        subfolder="text_encoder",
        cache_dir=cache_dir,
        revision="fp16",
    )

    vae = AutoencoderKL.from_pretrained(
        model,
        subfolder="vae",
        cache_dir=cache_dir,
        revision="fp16",
    )

    unet = UNet2DConditionModel.from_pretrained(
        model,
        subfolder="unet",
        cache_dir=cache_dir,
        revision="fp16",
    )

    noise_scheduler = DDPMScheduler.from_config(
        model,
        subfolder="scheduler",
        cache_dir=cache_dir,
    )
